import java.io.FileInputStream
import java.util.Properties

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.compose.compiler)
}

// Signing credentials configuration for release vs debug builds.
val keystorePropertiesFile = rootProject.file("keystore.properties")
val keystoreProperties = Properties().apply {
    if (keystorePropertiesFile.exists()) load(FileInputStream(keystorePropertiesFile))
}

fun signingValue(propKey: String, gradleKey: String): String? =
    keystoreProperties.getProperty(propKey) ?: providers.gradleProperty(gradleKey).orNull

val releaseStoreFile = signingValue("storeFile", "RELEASE_STORE_FILE")
val releaseStorePassword = signingValue("storePassword", "RELEASE_STORE_PASSWORD")
val releaseKeyAlias = signingValue("keyAlias", "RELEASE_KEY_ALIAS")
val releaseKeyPassword = signingValue("keyPassword", "RELEASE_KEY_PASSWORD")
val canSignRelease = releaseStoreFile != null && file(releaseStoreFile).exists()

// Determine if building for Google Play (-PplayBuild=true) or Sovereign build (Zapstore/GitHub)
val playBuild = when (providers.gradleProperty("playBuild").orNull?.lowercase()) {
    null -> false
    "", "true", "1", "yes" -> true
    "false", "0", "no" -> false
    else -> error("-PplayBuild property must be boolean")
}

// The city catalogue is generated by SunApp/update_cities.py and shared with the web app
// and every sibling Labs app. It is copied into assets at build time rather than checked
// in twice, because two copies would drift.
val cityAssetsDir = layout.buildDirectory.dir("generated/assets/cities")

kotlin {
    // The box default is a JDK 25 JRE with no compiler. Pin the toolchain so the
    // build does not depend on whatever JAVA_HOME happens to be. Byte reproduction
    // additionally needs Temurin 21.0.12.1+1; see android/README.md.
    jvmToolchain(21)
}

android {
    namespace = "no.stormberry.moonapp"
    compileSdk = 37

    defaultConfig {
        // Sovereign build: no.stormberry.moonapp
        // Google Play build: no.stormberry.moonapp.play
        applicationId = if (playBuild) "no.stormberry.moonapp.play" else "no.stormberry.moonapp"
        minSdk = 24
        targetSdk = 36

        // TWO NUMBER LINES, ONE CODEBASE. Follows the convention set on UsernameGenerator
        // 2026-09-03: a build's channel should be obvious from its version alone, so Play
        // does not share the sovereign numbering. Play requires monotonicity only within its
        // own package, and the two application IDs are separate packages to Android, so
        // nothing forces the lines to track each other.
        //
        // Sovereign 1.0.0 (code 1): the first Zapstore release. Nothing has shipped yet, so
        // this is a clean start rather than a continuation.
        //
        // Play 1.1.0 (code 2): RESERVED, not yet released. Play comes second, and the rule
        // from UsernameGenerator holds here too: every Play upload must be built from a
        // sovereign tag that already shipped, same code, different application ID and
        // different signature. Never respin Play from an untagged tree. Confirm these two
        // numbers at Play launch rather than assuming them, because the sovereign line may
        // have advanced past 1.0.0 by then.
        versionCode = if (playBuild) 2 else 1
        versionName = if (playBuild) "1.1.0" else "1.0.0"

        vectorDrawables.generatedDensities()

    }

    signingConfigs {
        if (canSignRelease) {
            create("release") {
                storeFile = file(releaseStoreFile!!)
                storePassword = releaseStorePassword
                keyAlias = releaseKeyAlias
                keyPassword = releaseKeyPassword
                enableV1Signing = false
                enableV2Signing = true
                enableV3Signing = true
            }
        }
    }

    buildTypes {
        release {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
            if (canSignRelease) signingConfig = signingConfigs.getByName("release")
        }
        debug {
            applicationIdSuffix = ".debug"
            versionNameSuffix = "-debug"
        }
    }

    sourceSets["main"].assets.directories.add(cityAssetsDir.get().asFile.absolutePath)

    buildFeatures {
        compose = true
        buildConfig = false
    }

    compileOptions {
        // java.time is API 26 and minSdk is 24, so without desugaring the app throws
        // NoClassDefFoundError on API 24 and 25. assembleRelease succeeds either way;
        // only lint catches it, which is why the release pipeline must run lint.
        isCoreLibraryDesugaringEnabled = true
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    lint {
        // Ship-blocking rather than advisory: the desugaring gap above is only visible here.
        abortOnError = true
    }

    packaging {
        resources {
            excludes += setOf(
                "/META-INF/{AL2.0,LGPL2.1}",
                "DebugProbesKt.bin",
                "kotlin-tooling-metadata.json"
            )
        }
    }
}

val copyCityData by tasks.registering(Copy::class) {
    description = "Copies the packed city catalogue from the repo root into app assets."
    group = "build"
    from(rootProject.file("../data")) {
        include("cities.tsv")
    }
    into(cityAssetsDir.map { it.dir("data") })
    // Deterministic ordering, so the APK is byte-reproducible across machines.
    duplicatesStrategy = DuplicatesStrategy.FAIL
}

tasks.named("preBuild") { dependsOn(copyCityData) }

dependencies {
    coreLibraryDesugaring(libs.desugar.jdk.libs)
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.activity.compose)
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.compose.ui)
    implementation(libs.androidx.compose.ui.graphics)
    implementation(libs.androidx.compose.material3)

    // Plain JUnit only. The lunar maths, the occurrence engine and the city search are all
    // pure functions or take a Reader, so none of them needs a device or Robolectric.
    testImplementation(libs.junit)
}
